### ISSUE TITLE
Community Exchange Introduction/Tracking

### ISSUE THREAD

**Issue by harshiniks** [sanjay-kv/Stackoverflow-Analysis#1]
👋 Hi @sanjay-kv,

I am your GitHub mentor for the GitHub Education, [Community Exchange](https://airtable.com/shrRJ3AvEZQohOdGV) (CX) project. I'll be collaborating with you on preparing your repo for CX.

You mentioned in your submission that you wanted to submit a Learn + Collaborate repo. This means that you would like to teach students, step by step, how to build this project as well as invite other students to collaborate and add features to this repo. I will generate issues, which will provide guidance on how to prepare your repo for a Learn + Collaborate CX submission on June 1, 2022.

This issue will serve as a tracking issue to track all issues related to CX. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch.

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated.

I look forward to working with you :octocat: 

CX Issues

- [x] https://github.com/sanjay-kv/Stackoverflow-Analysis/issues/2
- [x] https://github.com/sanjay-kv/Stackoverflow-Analysis/issues/3
- [x] https://github.com/sanjay-kv/Stackoverflow-Analysis/issues/4
- [x] https://github.com/sanjay-kv/Stackoverflow-Analysis/issues/5
- [x] https://github.com/sanjay-kv/Stackoverflow-Analysis/issues/6

**Comment by sanjay-kv** [comment]
All the Tasks completed @harshiniks, Please review them.
